export const GLOSSARY: Record<string, string> = {
  "AI": "Artificial intelligence. Systems that perform tasks that usually require human intelligence.",
  "machine learning": "A subset of AI where models learn patterns from data to make predictions or decisions.",
  "deep learning": "Machine learning using neural networks with multiple layers, often effective for unstructured data.",
  "neural network": "A model inspired by the brain, made of layers of connected nodes that transform inputs into outputs.",
  "NLP": "Natural language processing. Techniques for computers to understand and generate human language.",
  "reinforcement learning": "Learning by trial and error using rewards to optimise behaviour over time.",
  "VWFA": "Visual Word Form Area. A region in the brain linked to recognising written words quickly.",

  "cloak": "A loose outer garment that hangs from the shoulders.",
  "spectacles": "Eyeglasses used to help people see more clearly.",
  "crooked": "Bent or not straight in shape.",
  "soaring": "Flying or moving high in the air.",
  "parcel": "A wrapped package.",
  "vast": "Very large in size or extent.",
  "muscular": "Having strong, well-developed muscles.",
  "bundle": "A group of things tied or wrapped together.",
  "tuft": "A small bunch of hair or fibres growing close together.",
  "furiously": "With intense energy or emotion, often quickly or angrily.",
  "doorstep": "The step directly outside the door of a house.",

  "environmental disease": "A disease caused largely by environmental or lifestyle factors rather than genetics.",
  "heredity": "The passing of genetic traits from parents to children.",
  "obesity": "A medical condition involving excessive body fat.",
  "pollutants": "Substances that contaminate the environment.",
  "genetic material": "Biological molecules such as DNA that carry genetic information.",
  "oncogene": "A gene that can cause cancer when it becomes overactive or mutated.",
  "tumor suppressor gene": "A gene that normally prevents uncontrolled cell growth.",
  "biopsy": "A medical test where a small sample of tissue is removed for examination.",
  "specimen": "A sample used for scientific examination.",
  "malignancy": "The presence of cancerous cells that can spread.",
  "symptomatic": "Showing symptoms of a disease.",
  "radiographic": "Relating to imaging using X-rays or similar radiation.",
  "chemotherapy": "Treatment of disease, especially cancer, using drugs.",
  "radiotherapy": "Treatment using radiation to destroy cancer cells.",
  "prognosis": "The predicted course or outcome of a disease.",
  "histology": "The study of the microscopic structure of tissues.",
  "epithelial cells": "Cells that line surfaces and cavities of the body.",
  "connective tissue": "Tissue that supports or connects other tissues in the body.",
  "hematopoietic cells": "Cells responsible for producing blood cells.",
  "totipotent cells": "Cells capable of developing into any type of cell in an organism.",
  "embryonic tissue": "Tissue found in the early stages of development before birth.",
  "ulceration": "The formation of open sores on skin or tissue.",
  "compression": "Pressure applied to surrounding tissues or organs.",
  "jaundice": "A condition causing yellowing of the skin and eyes due to liver problems.",
  "metastasis": "The spread of cancer from one part of the body to another.",
  "hemoptysis": "Coughing up blood from the respiratory tract.",
  "hepatomegaly": "Abnormal enlargement of the liver.",
  "neurological": "Related to the nervous system and the brain.",
  "cachexia": "Extreme weight loss and weakness due to chronic illness.",
  "anemia": "A condition where the blood lacks enough healthy red blood cells.",
  "paraneoplastic": "Symptoms caused by cancer but not directly by the tumor itself.",
  "thrombosis": "Formation of a blood clot inside a blood vessel.",
  "pathogenesis": "The process by which a disease develops.",
  "DNA mutation": "A permanent change in the DNA sequence.",
  "mutagen": "A substance that causes changes in DNA.",
  "carcinogen": "A substance that can cause cancer.",
  "replication": "The process of copying DNA.",
  "nitrosamines": "Chemical compounds, often found in tobacco smoke, that can cause cancer.",
  "polycyclic aromatic hydrocarbons": "A group of chemicals produced by burning organic materials that can cause cancer.",
  "ionizing radiation": "High-energy radiation capable of removing electrons from atoms.",
  "ultraviolet radiation": "Radiation from the sun that can damage skin and cause cancer.",
  "non-ionizing radiation": "Low-energy radiation that does not remove electrons from atoms.",
  "carcinoma": "Cancer that begins in skin or tissues lining organs.",
  "sarcoma": "Cancer that develops in connective tissues like bone or muscle.",
  "lymphoma": "Cancer affecting the lymphatic system.",
  "leukemia": "Cancer of blood-forming tissues affecting white blood cells.",

  "academic discipline": "A specific branch of study or field of knowledge at a university.",
  "jurisprudence": "The theory or philosophy of law.",
  "legal framework": "The system of laws and regulations governing a society.",
  "doctrine": "A principle or rule that forms part of a system of belief or law.",
  "interpretation": "The act of explaining the meaning of laws or texts.",
  "precedent": "A previous legal decision used as a guide in future cases.",

  "residential": "Relating to places where people live.",
  "councillors": "Elected members of a local government council.",
  "Heavy Goods Vehicles": "Large trucks used to transport goods.",
  "low-loader": "A truck with a very low trailer used for transporting heavy equipment.",
  "disruption": "A disturbance that interrupts normal activity.",
  "navigation apps": "Mobile applications that provide directions using GPS.",
  "intervention": "Action taken to improve or change a situation.",
  "signage": "Signs used to give information or directions.",
  "jurisdiction": "The official power to make legal decisions or enforce laws.",
  "local authorities": "Government bodies responsible for managing local public services.",
  "infrastructure": "Basic systems and structures such as roads and transport networks.",
  "wedged": "Stuck tightly between objects.",
  "Gaeltacht": "An Irish-speaking region of Ireland where the Irish language is commonly used.",
  "priced out": "Unable to afford something because prices are too high.",
  "short-term lets": "Properties rented for short periods, often to tourists.",
  "marketed": "Promoted or advertised for sale.",
  "nestled": "Situated comfortably or securely within something.",
  "romantic idea": "An appealing or idealised view of a situation."
};